export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const DELETE_ITEM = 'DELETE_ITEM';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const TOGGLE_COMPLETE_ITEM = 'TOGGLE_COMPLETE_ITEM';